-- Generated by generate_physical_layer.py from {{KB_DB}}.KNOWLEDGE_BASE.KB_TERM
-- 266 column definitions across 6 tables.
-- Do not hand-edit: re-run the generator after reloading the KB.

CREATE DATABASE IF NOT EXISTS {{DB}}
  COMMENT = 'Physical layer, schema generated from the semantic knowledge base';
USE DATABASE {{DB}};

CREATE SCHEMA IF NOT EXISTS COMMON_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS;

-- DIM_US_PROD_CUSTOMERS: 104 columns, generated from KB_TERM
CREATE OR REPLACE TABLE COMMON_ANALYTICS.CUSTOMERS_US (
    ACCOUNT_NUMBER                     VARCHAR,
    ACCR_REC_TYPE                      VARCHAR,
    ACTIVE_USLEEP_CUSTOMER_FLAG        VARCHAR,
    ADDRESS1                           VARCHAR,
    ADDRESS2                           VARCHAR,
    ADDRESS3                           VARCHAR,
    ADDRESS4                           VARCHAR,
    AREA                               VARCHAR,
    AVERAGE_DAYS_DELINQUENT            VARCHAR,
    AVERAGE_DAYS_DELINQUENT6M          VARCHAR,
    BILL_TO_DM_EMAIL                   VARCHAR,
    BILL_TO_DM_ID                      NUMBER(38,0),
    BILL_TO_DM_NAME                    VARCHAR,
    BILL_TO_RM_EMAIL                   VARCHAR,
    BILL_TO_RM_ID                      NUMBER(38,0),
    BILL_TO_RM_NAME                    VARCHAR,
    BILL_TO_SALES_REP_EMAIL            VARCHAR,
    BILL_TO_SALES_REP_ID               NUMBER(38,0),
    BILL_TO_SALES_REP_NAME             VARCHAR,
    BUSINESS_TYPE_SITE                 VARCHAR,
    CATEGORY_CODE                      VARCHAR,
    CITY                               VARCHAR,
    COLLECTOR_ID                       NUMBER(38,0),
    COLLECTOR_NAME                     VARCHAR,
    COUNTRY                            VARCHAR,
    CREATION_DATE                      DATE,
    CREDIT_LIMIT_CHANGED_DATE          DATE,
    CREDIT_LIMIT_CHANGED_USER          VARCHAR,
    CURRENT_CREDIT_LIMIT               NUMBER(38,0),
    CURR_USLEEP_TGT_ACCOUNT_IND        VARCHAR,
    CUSTOMER_CLASS_CODE                VARCHAR,
    CUSTOMER_COUNTRY                   VARCHAR,
    CUSTOMER_COUNTY                    VARCHAR,
    CUSTOMER_ID                        NUMBER(38,0),
    CUSTOMER_NAME                      VARCHAR,
    CUSTOMER_NUMBER                    VARCHAR,
    CUSTOMER_TIER1                     VARCHAR,
    CUSTOMER_TIER10                    VARCHAR,
    CUSTOMER_TIER11                    VARCHAR,
    CUSTOMER_TIER2                     VARCHAR,
    CUSTOMER_TIER3                     VARCHAR,
    CUSTOMER_TIER4                     VARCHAR,
    CUSTOMER_TIER5                     VARCHAR,
    CUSTOMER_TIER6                     VARCHAR,
    CUSTOMER_TIER7                     VARCHAR,
    CUSTOMER_TIER8                     VARCHAR,
    CUSTOMER_TIER9                     VARCHAR,
    CUSTOMER_TYPE                      VARCHAR,
    CUST_ACCT_SITES_STATUS             VARCHAR,
    CUST_ACCT_SITE_ID                  NUMBER(38,0),
    CUST_LOC_PRICE_LIST_ID             NUMBER(38,2),
    CUST_LOC_PRICE_LIST_NAME           VARCHAR,
    CUST_SEGMENT                       VARCHAR,
    DATA_LOAD_TIME                     DATE,
    DATA_UPDATE_TIME                   DATE,
    DEFAULT_WAREHOUSE                  VARCHAR,
    DEFAULT_WAREHOUSE_ID               NUMBER(38,0),
    DM_SITE                            VARCHAR,
    FREIGHT_TERM                       VARCHAR,
    HOSPITAL_FLAG                      VARCHAR,
    HST_FLAG                           VARCHAR,
    HZ_PARTIES_PARTY_ID                NUMBER(38,0),
    JOIN_POSTAL_CODE                   VARCHAR,
    JOIN_PRICE_LIST_ID                 NUMBER(38,2),
    LATIN_AMERICA_CUSTOMER_FLAG        VARCHAR,
    LOCATION_ID                        NUMBER(38,0),
    MG_ELIGIBLE_FLAG                   VARCHAR,
    MG_SHIP_TO_FLAG                    VARCHAR,
    OLD_CREDIT_LIMIT                   NUMBER(38,0),
    OLD_PAYMENT_TERM                   VARCHAR,
    OLD_PAYMENT_TERM_ID                NUMBER(38,0),
    ON_CREDIT_HOLD                     VARCHAR,
    ORG_ID                             NUMBER(38,0),
    PARTY_ID                           NUMBER(38,0),
    PARTY_NUMBER                       VARCHAR,
    PARTY_SITE_ID                      NUMBER(38,0),
    PARTY_SITE_NUMBER                  VARCHAR,
    PAYMENT_TERM                       VARCHAR,
    PAYMENT_TERM_CHANGED_DATE          DATE,
    PAYMENT_TERM_CHANGED_USER          VARCHAR,
    PAYMENT_TERM_ID                    NUMBER(38,0),
    POSTAL_CODE                        VARCHAR,
    PREV_USLEEP_TGT_ACCOUNT_IND        VARCHAR,
    PRICE_LIST_ID                      NUMBER(38,2),
    PRICE_LIST_NAME                    VARCHAR,
    PRIMARY_SALES_REP_ID               NUMBER(38,0),
    PRIMARY_SALES_REP_NAME             VARCHAR,
    PROMOTIONAL_PRICING_INFO           VARCHAR,
    PROVINCE                           VARCHAR,
    REBATE_CUSTOMER_FLAG               VARCHAR,
    REGION                             VARCHAR,
    RM_SITE                            VARCHAR,
    SALESREP_ROLE_CODE                 VARCHAR,
    SALESREP_SITE                      VARCHAR,
    SAM_FLAG                           VARCHAR,
    SITE_CREATION_DATE                 DATE,
    SITE_NAME                          VARCHAR,
    SITE_USE_CODE                      VARCHAR,
    SITE_USE_ID                        NUMBER(38,0),
    SLEEPER_SEGMENTATION               VARCHAR,
    SLEEP_LAB_SEGMENT                  VARCHAR,
    STATE                              VARCHAR,
    STATUS                             VARCHAR,
    TERRITORY                          VARCHAR
)
COMMENT = 'Generated from {{KB_DB}} KB_TERM for Cognos query subject DIM_US_PROD_CUSTOMERS';

-- DIM_TIME: 24 columns, generated from KB_TERM
CREATE OR REPLACE TABLE COMMON_ANALYTICS.DIM_DATE (
    BUSINESS_DAY_FLAG                  NUMBER(38,0),
    CALENDAR_MONTH_ID                  NUMBER(38,0),
    CALENDAR_MONTH_NAME                VARCHAR,
    CALENDAR_QUARTER_ID                NUMBER(38,0),
    CALENDAR_QUARTER_NAME              VARCHAR,
    CALENDAR_YEAR_ID                   NUMBER(38,0),
    CALENDAR_YEAR_NAME                 VARCHAR,
    DATA_LOAD_TIME                     DATE,
    DATA_UPDATE_TIME                   DATE,
    DAY_DATE                           DATE,
    DAY_NUMBER                         NUMBER(38,0),
    DAY_WORK_NUMBER                    NUMBER(38,0),
    END_WEEK_NAME                      VARCHAR,
    FISCAL_MONTH_ID                    NUMBER(38,0),
    FISCAL_MONTH_NAME                  VARCHAR,
    FISCAL_QUARTER_ID                  NUMBER(38,0),
    FISCAL_QUARTER_NAME                VARCHAR,
    FISCAL_QUARTER_YEAR                VARCHAR,
    FISCAL_YEAR_ID                     NUMBER(38,0),
    FISCAL_YEAR_NAME                   VARCHAR,
    MONTH_YEAR                         VARCHAR,
    START_OF_WEEK                      DATE,
    START_WEEK_NAME                    VARCHAR,
    WEEK_NUMBER_OF_YEAR                NUMBER(38,0)
)
COMMENT = 'Generated from {{KB_DB}} KB_TERM for Cognos query subject DIM_TIME';

-- EDW_ORA_COA_PROD_GFP_W_NORA: 16 columns, generated from KB_TERM
CREATE OR REPLACE TABLE COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA (
    DATA_LOAD_TIME                     DATE,
    DATA_UPDATE_TIME                   DATE,
    ENDED_DATE                         VARCHAR,
    GFP_GROUP                          VARCHAR,
    GPC1                               VARCHAR,
    GPC2                               VARCHAR,
    GPC3                               VARCHAR,
    GPC4                               VARCHAR,
    INVENTORY_ITEM_DESC                VARCHAR,
    INVENTORY_ITEM_ID                  NUMBER(38,0),
    ITEM_NO                            VARCHAR,
    ROW_CREATE_DATE                    VARCHAR,
    ROW_UPDATE_DATE                    VARCHAR,
    SOFT_DELETE_IND                    VARCHAR,
    SOURCE                             VARCHAR,
    TGT_MD5                            VARCHAR
)
COMMENT = 'Generated from {{KB_DB}} KB_TERM for Cognos query subject EDW_ORA_COA_PROD_GFP_W_NORA';

-- FACT_BOOKED_SUMMARY: 33 columns, generated from KB_TERM
CREATE OR REPLACE TABLE SALES_ANALYTICS.FACT_BOOKED_SUMMARY (
    ADJUST_STATUS                      VARCHAR,
    COMM_LINES_API_ID                  NUMBER(38,0),
    CONSIGNMENT_ACCOUNT_NAME           VARCHAR,
    CONSIGNMENT_ACCOUNT_NUMBER         NUMBER(38,0),
    CUSTOMER_TRX_LINE_ID               NUMBER(38,0),
    CUST_ACCT_SITE_ID                  NUMBER(38,0),
    DATA_LOAD_TIME                     DATE,
    DATA_UPDATE_TIME                   DATE,
    DISCOUNT_TYPE                      VARCHAR,
    INVENTORY_ITEM_ID                  NUMBER(38,0),
    KIT_INVENTORY_ITEM_ID              NUMBER(38,0),
    LOAD_STATUS                        VARCHAR,
    ORDER_CATEGORY                     VARCHAR,
    ORDER_LINE_ID                      NUMBER(38,0),
    ORDER_TYPE                         VARCHAR,
    ORIGINAL_TRX_TYPE                  VARCHAR,
    PERIOD_DATE                        DATE,
    PROCESSED_DATE                     DATE,
    QUANTITY                           NUMBER(38,2),
    QUANTITY_EXCL_RESUPPLY             NUMBER(38,2),
    SPLIT_SOURCE_ACCOUNT_NAME          VARCHAR,
    SPLIT_SOURCE_ACCOUNT_NUMBER        VARCHAR,
    SPLIT_SOURCE_SITE_NUMBER           VARCHAR,
    TRACING_SOURCE_ACCOUNT_NAME        VARCHAR,
    TRACING_SOURCE_ACCOUNT_NUMBER      NUMBER(38,0),
    TRANSACTION_AMOUNT                 NUMBER(38,2),
    TRANSACTION_AMOUNT_EXCL_RESPLY     NUMBER(38,2),
    TRANSACTION_AMOUNT_USD             NUMBER(38,2),
    TRANSACTION_CURRENCY_CODE          VARCHAR,
    TRANSACTION_TYPE                   VARCHAR,
    TRANSACTION_TYPE_DESC              VARCHAR,
    TRANSACTION_TYPE_INVOICE           VARCHAR,
    TRAN_AMT_EXCL_RESPLY_USD           NUMBER(38,2)
)
COMMENT = 'Generated from {{KB_DB}} KB_TERM for Cognos query subject FACT_BOOKED_SUMMARY';

-- FACT_SALES_SUMMARY: 33 columns, generated from KB_TERM
CREATE OR REPLACE TABLE SALES_ANALYTICS.FACT_SALES_SUMMARY (
    ADJUST_STATUS                      VARCHAR,
    COMM_LINES_API_ID                  NUMBER(38,0),
    CONSIGNMENT_ACCOUNT_NAME           VARCHAR,
    CONSIGNMENT_ACCOUNT_NUMBER         NUMBER(38,0),
    CUSTOMER_TRX_LINE_ID               NUMBER(38,0),
    CUST_ACCT_SITE_ID                  NUMBER(38,0),
    DATA_LOAD_TIME                     DATE,
    DATA_UPDATE_TIME                   DATE,
    DISCOUNT_TYPE                      VARCHAR,
    INVENTORY_ITEM_ID                  NUMBER(38,0),
    KIT_INVENTORY_ITEM_ID              NUMBER(38,0),
    LOAD_STATUS                        VARCHAR,
    ORDER_CATEGORY                     VARCHAR,
    ORDER_LINE_ID                      NUMBER(38,0),
    ORDER_TYPE                         VARCHAR,
    ORIGINAL_TRX_TYPE                  VARCHAR,
    PERIOD_DATE                        DATE,
    PROCESSED_DATE                     DATE,
    QUANTITY                           NUMBER(38,2),
    QUANTITY_EXCL_RESUPPLY             NUMBER(38,2),
    SPLIT_SOURCE_ACCOUNT_NAME          VARCHAR,
    SPLIT_SOURCE_ACCOUNT_NUMBER        VARCHAR,
    SPLIT_SOURCE_SITE_NUMBER           VARCHAR,
    TRACING_SOURCE_ACCOUNT_NAME        VARCHAR,
    TRACING_SOURCE_ACCOUNT_NUMBER      NUMBER(38,0),
    TRANSACTION_AMOUNT                 NUMBER(38,2),
    TRANSACTION_AMOUNT_EXCL_RESPLY     NUMBER(38,2),
    TRANSACTION_AMOUNT_USD             NUMBER(38,2),
    TRANSACTION_CURRENCY_CODE          VARCHAR,
    TRANSACTION_TYPE                   VARCHAR,
    TRANSACTION_TYPE_DESC              VARCHAR,
    TRANSACTION_TYPE_INVOICE           VARCHAR,
    TRAN_AMT_EXCL_RESPLY_USD           NUMBER(38,2)
)
COMMENT = 'Generated from {{KB_DB}} KB_TERM for Cognos query subject FACT_SALES_SUMMARY';

-- TERRITORY_SITE_SALES_PERSON: 56 columns, generated from KB_TERM
CREATE OR REPLACE TABLE SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON (
    CUST_ACCT_SITE_ID                  NUMBER(38,0),
    DATA_LOAD_TIME                     DATE,
    DATA_UPDATE_TIME                   DATE,
    HIERARCHY_TYPE                     VARCHAR,
    L1_DIST_EMAIL_ID                   VARCHAR,
    L1_HIRE_DATE                       DATE,
    L1_SALES_PERSON_EMAIL_ID           VARCHAR,
    L1_SALES_PERSON_ID                 NUMBER(38,0),
    L1_SALES_PERSON_NAME               VARCHAR,
    L1_SALES_PERSON_NUMBER             VARCHAR,
    L1_SALES_PERSON_ROLE_NAME          VARCHAR,
    L2_DIST_EMAIL_ID                   VARCHAR,
    L2_HIRE_DATE                       DATE,
    L2_SALES_PERSON_EMAIL_ID           VARCHAR,
    L2_SALES_PERSON_ID                 NUMBER(38,0),
    L2_SALES_PERSON_NAME               VARCHAR,
    L2_SALES_PERSON_NUMBER             VARCHAR,
    L2_SALES_PERSON_ROLE_NAME          VARCHAR,
    L3_DIST_EMAIL_ID                   VARCHAR,
    L3_HIRE_DATE                       DATE,
    L3_SALES_PERSON_EMAIL_ID           VARCHAR,
    L3_SALES_PERSON_ID                 NUMBER(38,0),
    L3_SALES_PERSON_NAME               VARCHAR,
    L3_SALES_PERSON_NUMBER             VARCHAR,
    L3_SALES_PERSON_ROLE_NAME          VARCHAR,
    L4_DIST_EMAIL_ID                   VARCHAR,
    L4_HIRE_DATE                       DATE,
    L4_RESOURCE_ID                     NUMBER(38,0),
    L4_SALES_PERSON_ACTIVE_FLAG        VARCHAR,
    L4_SALES_PERSON_EMAIL_ID           VARCHAR,
    L4_SALES_PERSON_END_DATE           DATE,
    L4_SALES_PERSON_ID                 NUMBER(38,0),
    L4_SALES_PERSON_NAME               VARCHAR,
    L4_SALES_PERSON_NUMBER             VARCHAR,
    L4_SALES_PERSON_RESOURCE_ID        NUMBER(38,0),
    L4_SALES_PERSON_ROLE_NAME          VARCHAR,
    L4_SALES_PERSON_START_DATE         DATE,
    L4_SALE_PERSON_TERR_ACTIVE_FLG     VARCHAR,
    L4_SALE_PERSON_TERR_END_DATE       DATE,
    L4_SALE_PERSON_TERR_START_DATE     DATE,
    ORG_ID                             NUMBER(38,0),
    ROLE                               VARCHAR,
    SITE_NUMBER                        NUMBER(38,0),
    SITE_USE_ID                        NUMBER(38,0),
    TERRITORY_END_DATE                 DATE,
    TERRITORY_ID                       NUMBER(38,0),
    TERRITORY_LEVEL1                   VARCHAR,
    TERRITORY_LEVEL2                   VARCHAR,
    TERRITORY_LEVEL3                   VARCHAR,
    TERRITORY_LEVEL4                   VARCHAR,
    TERRITORY_START_DATE               DATE,
    TERRITORY_TIME_PERIOD              VARCHAR,
    TERRITORY_TYPE                     VARCHAR,
    TERR_SITE_RELATION_END_DATE        DATE,
    TERR_SITE_RELATION_START_DATE      DATE,
    TERR_SITE_RELATION_TIME_PERIOD     VARCHAR
)
COMMENT = 'Generated from {{KB_DB}} KB_TERM for Cognos query subject TERRITORY_SITE_SALES_PERSON';

USE DATABASE {{DB}};

-- E1 (stitch) and E2 (determinants): monthly grain beside daily sales.
-- A naive join of this to FACT_SALES_SUMMARY on month repeats the forecast once
-- per selling day, which is the double count Cognos's determinants prevent.
CREATE OR REPLACE TABLE SALES_ANALYTICS.FACT_MONTHLY_FORECAST (
    FORECAST_MONTH_ID              NUMBER(38,0)  COMMENT 'YYYYMM. The determinant key: one row per month per product line per territory',
    FORECAST_MONTH_START           DATE,
    INVENTORY_ITEM_ID              NUMBER(38,0),
    TERRITORY_LEVEL4               VARCHAR,
    FORECAST_AMOUNT_USD            NUMBER(38,2)  COMMENT 'Monthly grain. Must be grouped to FORECAST_MONTH_ID before summing alongside daily facts',
    FORECAST_QUANTITY              NUMBER(38,0)
)
COMMENT = 'Monthly forecast. Deliberately coarser grain than FACT_SALES_SUMMARY so multi-grain behaviour is testable.';

-- E6 (semi-additive): a balance, not a flow. Summing this across dates is wrong;
-- the closing balance is the last reading in the period.
CREATE OR REPLACE TABLE SALES_ANALYTICS.FACT_WAREHOUSE_STOCK (
    SNAPSHOT_DATE                  DATE          COMMENT 'Balance date. Rollup across this column is LAST, not SUM',
    WAREHOUSE_CODE                 VARCHAR,
    INVENTORY_ITEM_ID              NUMBER(38,0),
    UNITS_ON_HAND                  NUMBER(38,0)  COMMENT 'Semi-additive: SUM across warehouses, LAST across time',
    STOCK_VALUE_USD                NUMBER(38,2)  COMMENT 'Semi-additive: SUM across warehouses, LAST across time'
)
COMMENT = 'Daily stock balance snapshot. Exists to make the closing-balance requirement (E6) demonstrable.';

-- E4 (non-PK/FK join): rate keyed by currency plus a validity date range, so the
-- join is BETWEEN rather than equality. No foreign key exists or could.
CREATE OR REPLACE TABLE COMMON_ANALYTICS.DIM_CURRENCY_CONVERSION (
    FROM_CURRENCY_CODE             VARCHAR,
    TO_CURRENCY_CODE               VARCHAR,
    START_DATE                     DATE,
    END_DATE                       DATE,
    CONVERSION_RATE                NUMBER(38,8)
)
COMMENT = 'Currency rates with validity windows. Joined on code plus date BETWEEN start and end -- the E4 non-key join.';

-- E3 (cross product): shares no dimension with the sales star. Any attempt to
-- report supplier alongside sales has no join path, which is the case Cognos
-- blocks with its cross-product governor.
CREATE OR REPLACE TABLE COMMON_ANALYTICS.DIM_SUPPLIER (
    SUPPLIER_ID                    NUMBER(38,0),
    SUPPLIER_NAME                  VARCHAR,
    SUPPLIER_COUNTRY               VARCHAR,
    CONTRACT_TIER                  VARCHAR
)
COMMENT = 'Deliberately unrelated to the sales star: no shared key. Used to show the E3 cross-product case.';
