USE DATABASE {{DB}};
-- 6 of 63 KB-described entities are materialised here.
-- 57 are described by the source model but not yet built in the warehouse.

COMMENT ON TABLE {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US IS 'DIM_US_PROD_CUSTOMERS -- 113 business terms (21 measures, 6 keys). Defined in the source Cognos DMR model; extracted to {{KB_DB}}.';
COMMENT ON TABLE {{DB}}.COMMON_ANALYTICS.DIM_DATE IS 'DIM_TIME -- 49 business terms (12 measures, 4 keys). Defined in the source Cognos DMR model; extracted to {{KB_DB}}.';
COMMENT ON TABLE {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA IS 'EDW_ORA_COA_PROD_GFP_W_NORA -- 23 business terms (0 measures, 3 keys). Defined in the source Cognos DMR model; extracted to {{KB_DB}}.';
COMMENT ON TABLE {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY IS 'FACT_BOOKED_SUMMARY -- 42 business terms (16 measures, 4 keys). Defined in the source Cognos DMR model; extracted to {{KB_DB}}.';
COMMENT ON TABLE {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY IS 'FACT_SALES_SUMMARY -- 42 business terms (16 measures, 4 keys). Defined in the source Cognos DMR model; extracted to {{KB_DB}}.';
COMMENT ON TABLE {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON IS 'TERRITORY_SITE_SALES_PERSON -- 59 business terms (11 measures, 14 keys). Defined in the source Cognos DMR model; extracted to {{KB_DB}}.';

COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."ACCOUNT_NUMBER" IS '[attribute] Account Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."ACCR_REC_TYPE" IS '[attribute] Accr Rec Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."ACTIVE_USLEEP_CUSTOMER_FLAG" IS '[attribute] Active Usleep Customer Flag (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."ADDRESS1" IS '[attribute] Address1 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."ADDRESS2" IS '[attribute] Address2 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."ADDRESS3" IS '[attribute] Address3 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."ADDRESS4" IS '[attribute] Address4 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."AREA" IS '[attribute] Area (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."AVERAGE_DAYS_DELINQUENT" IS '[attribute] Average Days Delinquent (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."AVERAGE_DAYS_DELINQUENT6M" IS '[attribute] Average Days Delinquent6M (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BILL_TO_DM_EMAIL" IS '[attribute] Bill To Dm Email (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BILL_TO_DM_ID" IS '[measure] Bill To Dm Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BILL_TO_DM_NAME" IS '[attribute] Bill To Dm Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BILL_TO_RM_EMAIL" IS '[attribute] Bill To Rm Email (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BILL_TO_RM_ID" IS '[measure] Bill To Rm Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BILL_TO_RM_NAME" IS '[attribute] Bill To Rm Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BILL_TO_SALES_REP_EMAIL" IS '[attribute] Bill To Sales Rep Email (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BILL_TO_SALES_REP_ID" IS '[measure] Bill To Sales Rep Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BILL_TO_SALES_REP_NAME" IS '[attribute] Bill To Sales Rep Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."BUSINESS_TYPE_SITE" IS '[attribute] Business Type Site (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CATEGORY_CODE" IS '[attribute] Category Code (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CITY" IS '[attribute] City (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."COLLECTOR_ID" IS '[measure] Collector Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."COLLECTOR_NAME" IS '[attribute] Collector Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."COUNTRY" IS '[attribute] Country (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CREATION_DATE" IS '[identifier] Creation Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CREDIT_LIMIT_CHANGED_DATE" IS '[identifier] Credit Limit Changed Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CREDIT_LIMIT_CHANGED_USER" IS '[attribute] Credit Limit Changed User (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CURRENT_CREDIT_LIMIT" IS '[measure] Current Credit Limit (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CURR_USLEEP_TGT_ACCOUNT_IND" IS '[attribute] Curr Usleep Tgt Account Ind (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_CLASS_CODE" IS '[attribute] Customer Class Code (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_COUNTRY" IS '[attribute] Customer Country (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_COUNTY" IS '[attribute] Customer County (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_ID" IS '[measure] Customer Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_NAME" IS '[attribute] Customer Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_NUMBER" IS '[attribute] Customer Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER1" IS '[attribute] Customer Tier1 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER10" IS '[attribute] Customer Tier10 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER11" IS '[attribute] Customer Tier11 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER2" IS '[attribute] Customer Tier2 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER3" IS '[attribute] Customer Tier3 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER4" IS '[attribute] Customer Tier4 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER5" IS '[attribute] Customer Tier5 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER6" IS '[attribute] Customer Tier6 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER7" IS '[attribute] Customer Tier7 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER8" IS '[attribute] Customer Tier8 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TIER9" IS '[attribute] Customer Tier9 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUSTOMER_TYPE" IS '[attribute] Customer Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUST_ACCT_SITES_STATUS" IS '[attribute] Cust Acct Sites Status (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUST_ACCT_SITE_ID" IS '[measure] Cust Acct Site Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUST_LOC_PRICE_LIST_ID" IS '[measure] Cust Loc Price List Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUST_LOC_PRICE_LIST_NAME" IS '[attribute] Cust Loc Price List Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."CUST_SEGMENT" IS '[attribute] Cust Segment (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."DATA_LOAD_TIME" IS '[identifier] Data Load Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."DATA_UPDATE_TIME" IS '[identifier] Data Update Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."DEFAULT_WAREHOUSE" IS '[attribute] Default Warehouse (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."DEFAULT_WAREHOUSE_ID" IS '[measure] Default Warehouse Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."DM_SITE" IS '[attribute] Dm Site (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."FREIGHT_TERM" IS '[attribute] Freight Term (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."HOSPITAL_FLAG" IS '[attribute] Hospital Flag (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."HST_FLAG" IS '[attribute] Hst Flag (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."HZ_PARTIES_PARTY_ID" IS '[measure] Hz Parties Party Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."JOIN_POSTAL_CODE" IS '[attribute] Join Postal Code (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."JOIN_PRICE_LIST_ID" IS '[measure] Join Price List Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."LATIN_AMERICA_CUSTOMER_FLAG" IS '[attribute] Latin America Customer Flag (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."LOCATION_ID" IS '[measure] Location Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."MG_ELIGIBLE_FLAG" IS '[attribute] Mg Eligible Flag (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."MG_SHIP_TO_FLAG" IS '[attribute] Mg Ship To Flag (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."OLD_CREDIT_LIMIT" IS '[measure] Old Credit Limit (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."OLD_PAYMENT_TERM" IS '[attribute] Old Payment Term (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."OLD_PAYMENT_TERM_ID" IS '[measure] Old Payment Term Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."ON_CREDIT_HOLD" IS '[attribute] On Credit Hold (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."ORG_ID" IS '[measure] Org Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PARTY_ID" IS '[measure] Party Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PARTY_NUMBER" IS '[attribute] Party Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PARTY_SITE_ID" IS '[measure] Party Site Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PARTY_SITE_NUMBER" IS '[attribute] Party Site Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PAYMENT_TERM" IS '[attribute] Payment Term (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PAYMENT_TERM_CHANGED_DATE" IS '[identifier] Payment Term Changed Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PAYMENT_TERM_CHANGED_USER" IS '[attribute] Payment Term Changed User (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PAYMENT_TERM_ID" IS '[measure] Payment Term Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."POSTAL_CODE" IS '[attribute] Postal Code (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PREV_USLEEP_TGT_ACCOUNT_IND" IS '[attribute] Prev Usleep Tgt Account Ind (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PRICE_LIST_ID" IS '[measure] Price List Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PRICE_LIST_NAME" IS '[attribute] Price List Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PRIMARY_SALES_REP_ID" IS '[measure] Primary Sales Rep Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PRIMARY_SALES_REP_NAME" IS '[attribute] Primary Sales Rep Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PROMOTIONAL_PRICING_INFO" IS '[attribute] Promotional Pricing Info (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."PROVINCE" IS '[attribute] Province (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."REBATE_CUSTOMER_FLAG" IS '[attribute] Rebate Customer Flag (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."REGION" IS '[attribute] Region (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."RM_SITE" IS '[attribute] Rm Site (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."SALESREP_ROLE_CODE" IS '[attribute] Salesrep Role Code (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."SALESREP_SITE" IS '[attribute] Salesrep Site (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."SAM_FLAG" IS '[attribute] Sam Flag (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."SITE_CREATION_DATE" IS '[identifier] Site Creation Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."SITE_NAME" IS '[attribute] Site Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."SITE_USE_CODE" IS '[attribute] Site Use Code (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."SITE_USE_ID" IS '[measure] Site Use Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."SLEEPER_SEGMENTATION" IS '[attribute] Sleeper Segmentation (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."SLEEP_LAB_SEGMENT" IS '[attribute] Sleep Lab Segment (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."STATE" IS '[attribute] State (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."STATUS" IS '[attribute] Status (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.CUSTOMERS_US."TERRITORY" IS '[attribute] Territory (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."BUSINESS_DAY_FLAG" IS '[measure] Bus Day Flg (auto-generated from the source name; not steward-reviewed) (BI name: BUS_DAY_FLG)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."CALENDAR_MONTH_ID" IS '[attribute] Cal Mth Id (auto-generated from the source name; not steward-reviewed) (BI name: CAL_MTH_ID)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."CALENDAR_MONTH_NAME" IS '[attribute] Cal Mth Nm (auto-generated from the source name; not steward-reviewed) (BI name: CAL_MTH_NM)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."CALENDAR_QUARTER_ID" IS '[attribute] Cal Qtr Id (auto-generated from the source name; not steward-reviewed) (BI name: CAL_QTR_ID)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."CALENDAR_QUARTER_NAME" IS '[attribute] Cal Qtr Nm (auto-generated from the source name; not steward-reviewed) (BI name: CAL_QTR_NM)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."CALENDAR_YEAR_ID" IS '[attribute] Cy Id (auto-generated from the source name; not steward-reviewed) (BI name: CY_ID)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."CALENDAR_YEAR_NAME" IS '[attribute] Cy Nm (auto-generated from the source name; not steward-reviewed) (BI name: CY_NM)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."DATA_LOAD_TIME" IS '[identifier] Data Load Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."DATA_UPDATE_TIME" IS '[identifier] Data Update Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."DAY_DATE" IS '[attribute] Day Dt (auto-generated from the source name; not steward-reviewed) (BI name: DAY_DT)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."DAY_NUMBER" IS '[attribute] Day Nbr (auto-generated from the source name; not steward-reviewed) (BI name: DAY_NBR)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."DAY_WORK_NUMBER" IS '[measure] Day Wrk Nbr (auto-generated from the source name; not steward-reviewed) (BI name: DAY_WRK_NBR)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."END_WEEK_NAME" IS '[attribute] End Wk Nm (auto-generated from the source name; not steward-reviewed) (BI name: END_WK_NM)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."FISCAL_MONTH_ID" IS '[attribute] Finc Mth Id (auto-generated from the source name; not steward-reviewed) (BI name: FINC_MTH_ID)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."FISCAL_MONTH_NAME" IS '[attribute] Finc Mth Nm (auto-generated from the source name; not steward-reviewed) (BI name: FINC_MTH_NM)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."FISCAL_QUARTER_ID" IS '[attribute] Finc Qtr Id (auto-generated from the source name; not steward-reviewed) (BI name: FINC_QTR_ID)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."FISCAL_QUARTER_NAME" IS '[attribute] Finc Qtr Nm (auto-generated from the source name; not steward-reviewed) (BI name: FINC_QTR_NM)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."FISCAL_QUARTER_YEAR" IS '[attribute] Finc Qtr Yr (auto-generated from the source name; not steward-reviewed) (BI name: FINC_QTR_YR)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."FISCAL_YEAR_ID" IS '[attribute] Finc Yr Id (auto-generated from the source name; not steward-reviewed) (BI name: FINC_YR_ID)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."FISCAL_YEAR_NAME" IS '[attribute] Finc Yr Nm (auto-generated from the source name; not steward-reviewed) (BI name: FINC_YR_NM)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."MONTH_YEAR" IS '[attribute] Mth Yr (auto-generated from the source name; not steward-reviewed) (BI name: MTH_YR)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."START_OF_WEEK" IS '[attribute] Sdt Of Wk (auto-generated from the source name; not steward-reviewed) (BI name: SDT_OF_WK)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."START_WEEK_NAME" IS '[attribute] Strt Wk Nm (auto-generated from the source name; not steward-reviewed) (BI name: STRT_WK_NM)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.DIM_DATE."WEEK_NUMBER_OF_YEAR" IS '[attribute] Wk Nbrf Yr (auto-generated from the source name; not steward-reviewed) (BI name: WK_NBRF_YR)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."DATA_LOAD_TIME" IS '[identifier] Data Load Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."DATA_UPDATE_TIME" IS '[identifier] Data Update Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."ENDED_DATE" IS '[attribute] Ended Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."GFP_GROUP" IS '[attribute] Gfp Group (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."GPC1" IS '[attribute] Gpc1 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."GPC2" IS '[attribute] Gpc2 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."GPC3" IS '[attribute] Gpc3 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."GPC4" IS '[attribute] Gpc4 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."INVENTORY_ITEM_DESC" IS '[attribute] Inventory Item Desc (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."INVENTORY_ITEM_ID" IS '[identifier] Inventory Item Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."ITEM_NO" IS '[attribute] Item No (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."ROW_CREATE_DATE" IS '[attribute] Row Create Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."ROW_UPDATE_DATE" IS '[attribute] Row Update Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."SOFT_DELETE_IND" IS '[attribute] Soft Delete Ind (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."SOURCE" IS '[attribute] Source (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.COMMON_ANALYTICS.EDW_ORA_COA_PROD_GFP_W_NORA."TGT_MD5" IS '[attribute] Tgt Md5 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."ADJUST_STATUS" IS '[attribute] Adjust Status (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."COMM_LINES_API_ID" IS '[measure] Comm Lines Api Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."CONSIGNMENT_ACCOUNT_NAME" IS '[attribute] Consignment Account Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."CONSIGNMENT_ACCOUNT_NUMBER" IS '[measure] Consignment Account Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."CUSTOMER_TRX_LINE_ID" IS '[measure] Customer Trx Line Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."CUST_ACCT_SITE_ID" IS '[measure] Cust Acct Site Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."DATA_LOAD_TIME" IS '[identifier] Data Load Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."DATA_UPDATE_TIME" IS '[identifier] Data Update Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."DISCOUNT_TYPE" IS '[attribute] Discount Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."INVENTORY_ITEM_ID" IS '[measure] Inventory Item Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."KIT_INVENTORY_ITEM_ID" IS '[measure] Kit Inventory Item Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."LOAD_STATUS" IS '[attribute] Load Status (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."ORDER_CATEGORY" IS '[attribute] Order Category (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."ORDER_LINE_ID" IS '[measure] Order Line Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."ORDER_TYPE" IS '[attribute] Order Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."ORIGINAL_TRX_TYPE" IS '[attribute] Original Trx Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."PERIOD_DATE" IS '[identifier] Period Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."PROCESSED_DATE" IS '[identifier] Processed Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."QUANTITY" IS '[measure] Quantity (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."QUANTITY_EXCL_RESUPPLY" IS '[measure] Quantity Excl Resupply (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."SPLIT_SOURCE_ACCOUNT_NAME" IS '[attribute] Split Source Account Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."SPLIT_SOURCE_ACCOUNT_NUMBER" IS '[attribute] Split Source Account Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."SPLIT_SOURCE_SITE_NUMBER" IS '[attribute] Split Source Site Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRACING_SOURCE_ACCOUNT_NAME" IS '[attribute] Tracing Source Account Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRACING_SOURCE_ACCOUNT_NUMBER" IS '[measure] Tracing Source Account Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRANSACTION_AMOUNT" IS '[measure] Transaction Amount (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRANSACTION_AMOUNT_EXCL_RESPLY" IS '[measure] Transaction Amount Excl Resply (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRANSACTION_AMOUNT_USD" IS '[measure] Transaction Amount Usd (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRANSACTION_CURRENCY_CODE" IS '[attribute] Transaction Currency Code (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRANSACTION_TYPE" IS '[attribute] Transaction Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRANSACTION_TYPE_DESC" IS '[attribute] Transaction Type Desc (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRANSACTION_TYPE_INVOICE" IS '[attribute] Transaction Type Invoice (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_BOOKED_SUMMARY."TRAN_AMT_EXCL_RESPLY_USD" IS '[measure] Tran Amt Excl Resply Usd (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."ADJUST_STATUS" IS '[attribute] Adjust Status (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."COMM_LINES_API_ID" IS '[measure] Comm Lines Api Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."CONSIGNMENT_ACCOUNT_NAME" IS '[attribute] Consignment Account Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."CONSIGNMENT_ACCOUNT_NUMBER" IS '[measure] Consignment Account Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."CUSTOMER_TRX_LINE_ID" IS '[measure] Customer Trx Line Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."CUST_ACCT_SITE_ID" IS '[measure] Cust Acct Site Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."DATA_LOAD_TIME" IS '[identifier] Data Load Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."DATA_UPDATE_TIME" IS '[identifier] Data Update Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."DISCOUNT_TYPE" IS '[attribute] Discount Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."INVENTORY_ITEM_ID" IS '[measure] Inventory Item Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."KIT_INVENTORY_ITEM_ID" IS '[measure] Kit Inventory Item Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."LOAD_STATUS" IS '[attribute] Load Status (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."ORDER_CATEGORY" IS '[attribute] Order Category (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."ORDER_LINE_ID" IS '[measure] Order Line Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."ORDER_TYPE" IS '[attribute] Order Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."ORIGINAL_TRX_TYPE" IS '[attribute] Original Trx Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."PERIOD_DATE" IS '[identifier] Period Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."PROCESSED_DATE" IS '[identifier] Processed Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."QUANTITY" IS '[measure] Quantity (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."QUANTITY_EXCL_RESUPPLY" IS '[measure] Quantity Excl Resupply (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."SPLIT_SOURCE_ACCOUNT_NAME" IS '[attribute] Split Source Account Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."SPLIT_SOURCE_ACCOUNT_NUMBER" IS '[attribute] Split Source Account Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."SPLIT_SOURCE_SITE_NUMBER" IS '[attribute] Split Source Site Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRACING_SOURCE_ACCOUNT_NAME" IS '[attribute] Tracing Source Account Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRACING_SOURCE_ACCOUNT_NUMBER" IS '[measure] Tracing Source Account Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRANSACTION_AMOUNT" IS '[measure] Transaction Amount (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRANSACTION_AMOUNT_EXCL_RESPLY" IS '[measure] Transaction Amount Excl Resply (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRANSACTION_AMOUNT_USD" IS '[measure] Transaction Amount Usd (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRANSACTION_CURRENCY_CODE" IS '[attribute] Transaction Currency Code (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRANSACTION_TYPE" IS '[attribute] Transaction Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRANSACTION_TYPE_DESC" IS '[attribute] Transaction Type Desc (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRANSACTION_TYPE_INVOICE" IS '[attribute] Transaction Type Invoice (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.FACT_SALES_SUMMARY."TRAN_AMT_EXCL_RESPLY_USD" IS '[measure] Tran Amt Excl Resply Usd (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."CUST_ACCT_SITE_ID" IS '[measure] Cust Acct Site Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."DATA_LOAD_TIME" IS '[identifier] Data Load Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."DATA_UPDATE_TIME" IS '[identifier] Data Update Time (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."HIERARCHY_TYPE" IS '[attribute] Hierarchy Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L1_DIST_EMAIL_ID" IS '[attribute] L1 Dist Email Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L1_HIRE_DATE" IS '[identifier] L1 Hire Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L1_SALES_PERSON_EMAIL_ID" IS '[attribute] L1 Sales Person Email Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L1_SALES_PERSON_ID" IS '[measure] L1 Sales Person Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L1_SALES_PERSON_NAME" IS '[attribute] L1 Sales Person Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L1_SALES_PERSON_NUMBER" IS '[attribute] L1 Sales Person Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L1_SALES_PERSON_ROLE_NAME" IS '[attribute] L1 Sales Person Role Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L2_DIST_EMAIL_ID" IS '[attribute] L2 Dist Email Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L2_HIRE_DATE" IS '[identifier] L2 Hire Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L2_SALES_PERSON_EMAIL_ID" IS '[attribute] L2 Sales Person Email Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L2_SALES_PERSON_ID" IS '[measure] L2 Sales Person Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L2_SALES_PERSON_NAME" IS '[attribute] L2 Sales Person Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L2_SALES_PERSON_NUMBER" IS '[attribute] L2 Sales Person Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L2_SALES_PERSON_ROLE_NAME" IS '[attribute] L2 Sales Person Role Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L3_DIST_EMAIL_ID" IS '[attribute] L3 Dist Email Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L3_HIRE_DATE" IS '[identifier] L3 Hire Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L3_SALES_PERSON_EMAIL_ID" IS '[attribute] L3 Sales Person Email Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L3_SALES_PERSON_ID" IS '[measure] L3 Sales Person Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L3_SALES_PERSON_NAME" IS '[attribute] L3 Sales Person Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L3_SALES_PERSON_NUMBER" IS '[attribute] L3 Sales Person Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L3_SALES_PERSON_ROLE_NAME" IS '[attribute] L3 Sales Person Role Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_DIST_EMAIL_ID" IS '[attribute] L4 Dist Email Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_HIRE_DATE" IS '[identifier] L4 Hire Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_RESOURCE_ID" IS '[measure] L4 Resource Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALES_PERSON_ACTIVE_FLAG" IS '[attribute] L4 Sales Person Active Flag (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALES_PERSON_EMAIL_ID" IS '[attribute] L4 Sales Person Email Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALES_PERSON_END_DATE" IS '[identifier] L4 Sales Person End Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALES_PERSON_ID" IS '[measure] L4 Sales Person Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALES_PERSON_NAME" IS '[attribute] L4 Sales Person Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALES_PERSON_NUMBER" IS '[attribute] L4 Sales Person Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALES_PERSON_RESOURCE_ID" IS '[measure] L4 Sales Person Resource Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALES_PERSON_ROLE_NAME" IS '[attribute] L4 Sales Person Role Name (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALES_PERSON_START_DATE" IS '[identifier] L4 Sales Person Start Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALE_PERSON_TERR_ACTIVE_FLG" IS '[attribute] L4 Sale Person Terr Active Flg (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALE_PERSON_TERR_END_DATE" IS '[identifier] L4 Sale Person Terr End Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."L4_SALE_PERSON_TERR_START_DATE" IS '[identifier] L4 Sale Person Terr Start Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."ORG_ID" IS '[measure] Org Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."ROLE" IS '[attribute] Role (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."SITE_NUMBER" IS '[measure] Site Number (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."SITE_USE_ID" IS '[measure] Site Use Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERRITORY_END_DATE" IS '[identifier] Territory End Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERRITORY_ID" IS '[measure] Territory Id (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERRITORY_LEVEL1" IS '[attribute] Territory Level1 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERRITORY_LEVEL2" IS '[attribute] Territory Level2 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERRITORY_LEVEL3" IS '[attribute] Territory Level3 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERRITORY_LEVEL4" IS '[attribute] Territory Level4 (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERRITORY_START_DATE" IS '[identifier] Territory Start Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERRITORY_TIME_PERIOD" IS '[attribute] Territory Time Period (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERRITORY_TYPE" IS '[attribute] Territory Type (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERR_SITE_RELATION_END_DATE" IS '[identifier] Terr Site Relation End Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERR_SITE_RELATION_START_DATE" IS '[identifier] Terr Site Relation Start Date (auto-generated from the source name; not steward-reviewed)';
COMMENT ON COLUMN {{DB}}.SALES_ANALYTICS.TERRITORY_SITE_SALES_PERSON."TERR_SITE_RELATION_TIME_PERIOD" IS '[attribute] Terr Site Relation Time Period (auto-generated from the source name; not steward-reviewed)';